[tool.poetry]
name = "load-to-supabase-s3"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.34.150"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
